language: node_js

node_js:
  - "6"

cache:
  directories:
    - "node_modules"

install:
  - npm install
before_script:
  - cp ./src/settings/example.ts ./src/settings/index.ts
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
    target_branch: gh-pages
